env: #react folder has its own eslintrc
  browser: true
  jquery: true
extends: ["eslint:recommended", "google"]
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  no-tabs: off
  linebreak-style:
    - error
    - unix
  quotes: off
  semi:
    - error
    - always
  max-len:
    - error
    - code: 180
      comments: 300
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  no-var: off
  comma-dangle: off
  prefer-spread: off
  no-implicit-globals: error
  valid-jsdoc: error
  no-undef: off
  no-multiple-empty-lines: 2
  prefer-rest-params: off
  new-cap: off
  require-jsdoc: off
globals:
  E: true
  Ext: true
